#!/bin/bash

backup-config

echo
echo
echo "Backing up coding/ to mantis:~/Documents/coding"
echo
rsync -azh --delete --info=progress2 ~/coding/ caldero@mantis.mathcs.carleton.edu:/Accounts/caldero/Documents/coding/
